export { buildFolderTree, countNotesWithinChildren, countUnfiledNotes } from './model/domain/folder-tree'
export { isDeletedNoteRetained, matchesNoteKeyword, normalizeParentIdKey, shouldRefreshNoteUpdated } from './model/domain/note-rules'
export { getNotesSync, initializeNotes, useNote } from './model/state/note-store'
export { useNoteRepository } from './model/use-note-repository'
export type { NoteRepository } from './model/use-note-repository'
export type { FolderTreeNode, Note } from '@/shared/types'
export { normalizeNoteLockFields, NOTE_LOCK_TYPE, NOTE_TYPE } from '@/shared/types'
