migrate((app) => {
  const snapshot = [
    {
      id: '_pb_users_auth_',
      listRule: 'id = @request.auth.id',
      viewRule: 'id = @request.auth.id',
      createRule: '',
      updateRule: 'id = @request.auth.id',
      deleteRule: 'id = @request.auth.id',
      name: 'users',
      type: 'auth',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cost: 0,
          hidden: true,
          id: 'password901924565',
          max: 0,
          min: 8,
          name: 'password',
          pattern: '',
          presentable: false,
          required: true,
          system: true,
          type: 'password',
        },
        {
          autogeneratePattern: '[a-zA-Z0-9]{50}',
          hidden: true,
          id: 'text2504183744',
          max: 60,
          min: 30,
          name: 'tokenKey',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: true,
          type: 'text',
        },
        {
          exceptDomains: null,
          hidden: false,
          id: 'email3885137012',
          name: 'email',
          onlyDomains: null,
          presentable: false,
          required: true,
          system: true,
          type: 'email',
        },
        {
          hidden: false,
          id: 'bool1547992806',
          name: 'emailVisibility',
          presentable: false,
          required: false,
          system: true,
          type: 'bool',
        },
        {
          hidden: false,
          id: 'bool256245529',
          name: 'verified',
          presentable: false,
          required: false,
          system: true,
          type: 'bool',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1579384326',
          max: 255,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'file376926767',
          maxSelect: 1,
          maxSize: 0,
          mimeTypes: [
            'image/jpeg',
            'image/png',
            'image/svg+xml',
            'image/gif',
            'image/webp',
          ],
          name: 'avatar',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: 'file',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text4166911607',
          max: 12,
          min: 5,
          name: 'username',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text818055786',
          max: 128,
          min: 0,
          name: 'note_lock_pin_salt',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1853949989',
          max: 128,
          min: 0,
          name: 'note_lock_pin_hash',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number2327901178',
          max: null,
          min: 1,
          name: 'note_lock_pin_version',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX `idx_tokenKey__pb_users_auth_` ON `users` (`tokenKey`)',
        'CREATE UNIQUE INDEX `idx_email__pb_users_auth_` ON `users` (`email`) WHERE `email` != \'\'',
        'CREATE UNIQUE INDEX `idx_username__pb_users_auth` ON `users` (`username`) WHERE `username` != \'\'',
      ],
      system: false,
      authRule: '',
      manageRule: null,
      authAlert: {
        enabled: true,
        emailTemplate: {
          subject: '【{APP_NAME}】安全提醒：检测到新地点登录',
          body: '<p>您好，</p>\n<p>我们检测到您的 {APP_NAME} 账户有一次来自新地点的登录。</p>\n<p>如果这是您本人操作，则无需理会本邮件。</p>\n<p><strong>如果这不是您本人操作，建议您立即更改 {APP_NAME} 账户密码，以保护您的账户安全。更改密码后，您的账户将会从所有其他设备上登出。</strong></p>\n<p>\n  此致，<br/>\n  {APP_NAME} 团队\n</p>',
        },
      },
      oauth2: {
        providers: [],
        mappedFields: {
          id: '',
          name: 'name',
          username: '',
          avatarURL: 'avatar',
        },
        enabled: false,
      },
      passwordAuth: {
        enabled: true,
        identityFields: [
          'email',
        ],
      },
      mfa: {
        enabled: false,
        duration: 1800,
        rule: '',
      },
      otp: {
        enabled: false,
        duration: 180,
        length: 8,
        emailTemplate: {
          subject: 'OTP for {APP_NAME}',
          body: '<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn\'t ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
        },
      },
      authToken: {
        duration: 604800,
      },
      passwordResetToken: {
        duration: 1800,
      },
      emailChangeToken: {
        duration: 1800,
      },
      verificationToken: {
        duration: 259200,
      },
      fileToken: {
        duration: 180,
      },
      verificationTemplate: {
        subject: '欢迎加入 {APP_NAME}！请验证您的邮箱',
        body: '<p>嗨，您好！</p>\n<p>欢迎来到 {APP_NAME} 的大家庭！</p>\n<p>请点击下面的按钮，完成最后一步邮箱验证哦。</p>\n<p>\n<a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">立即验证</a>\n</p>\n<p>\n祝您使用愉快！<br/>\n{APP_NAME} 团队\n</p>',
      },
      resetPasswordTemplate: {
        subject: '重置您的 {APP_NAME} 密码',
        body: '<p>您好，</p>\n<p>我们收到了一个重置您 {APP_NAME} 账户密码的请求。请点击下方按钮设置新密码：</p>\n<p>\n<a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">设置新密码</a>\n</p>\n<p><i>为保障您的账户安全，如果您没有进行此项操作，请忽略本邮件，切勿将此链接告知他人。</i></p>\n<p>\n感谢您的配合，<br/>\n{APP_NAME} 团队\n</p>',
      },
      confirmEmailChangeTemplate: {
        subject: '请确认您的 {APP_NAME} 新邮箱地址',
        body: '<p>您好，</p>\n<p>请点击下方的按钮，以确认您的新邮箱地址。</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">确认新邮箱</a>\n</p>\n<p><i>如果您并未请求更改邮箱地址，请忽略此邮件。</i></p>\n<p>\n  祝好，<br/>\n  {APP_NAME} 团队\n</p>',
      },
    },
    {
      id: 'pbc_3395098727',
      listRule: 'user_id = @request.auth.id || is_public = 1',
      viewRule: 'user_id = @request.auth.id || is_public = 1',
      createRule: '@request.auth.id != ""',
      updateRule: 'user_id = @request.auth.id',
      deleteRule: 'user_id = @request.auth.id',
      name: 'notes',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-zA-Z0-9_-]{12}',
          hidden: false,
          id: 'text3208210256',
          max: 12,
          min: 12,
          name: 'id',
          pattern: '^[a-zA-Z0-9-_]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: '_pb_users_auth_',
          hidden: false,
          id: 'relation1542800728',
          maxSelect: 1,
          minSelect: 0,
          name: 'user_id',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text724990059',
          max: 0,
          min: 0,
          name: 'title',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1882403891',
          max: 0,
          min: 0,
          name: 'summary',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          convertURLs: false,
          hidden: false,
          id: 'editor4274335913',
          maxSize: 0,
          name: 'content',
          presentable: false,
          required: false,
          system: false,
          type: 'editor',
        },
        {
          hidden: false,
          id: 'file104153177',
          maxSelect: 99,
          maxSize: 0,
          mimeTypes: [],
          name: 'files',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: [],
          type: 'file',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1431356653',
          max: 12,
          min: 12,
          name: 'parent_id',
          pattern: '^[A-Za-z0-9-_]+$',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number739690365',
          max: null,
          min: null,
          name: 'is_locked',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number1111565423',
          max: null,
          min: null,
          name: 'is_deleted',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number1811784642',
          max: null,
          min: null,
          name: 'is_public',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number4285180856',
          max: null,
          min: null,
          name: 'note_count',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number1156453330',
          max: null,
          min: null,
          name: 'item_type',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      indexes: [],
      system: false,
    },
    {
      id: 'pbc_83919930',
      listRule: '',
      viewRule: '',
      createRule: null,
      updateRule: null,
      deleteRule: null,
      name: 'public_users',
      type: 'view',
      fields: [
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3208210256',
          max: 0,
          min: 0,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_jfjk',
          max: 12,
          min: 5,
          name: 'username',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: '_clone_9I9u',
          max: 255,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: '_clone_wtn4',
          maxSelect: 1,
          maxSize: 0,
          mimeTypes: [
            'image/jpeg',
            'image/png',
            'image/svg+xml',
            'image/gif',
            'image/webp',
          ],
          name: 'avatar',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: 'file',
        },
      ],
      indexes: [],
      system: false,
      viewQuery: 'SELECT id, username, name, avatar FROM users',
    },
  ]

  return app.importCollections(snapshot, true)
})
