export {
  createAcceptString,
  FileCategory,
  formatFileSize,
  getFileCategoryByFilename,
  getFileCategoryByMimeType,
  getFileExtension,
  getFileIcon,
  getMimeTypeByExtension,
  getMimeTypeByFilename,
  isArchiveFile,
  isAudioFile,
  isDocumentFile,
  isFileTypeAllowed,
  isImageFile,
  isVideoFile,
  MIME_TYPES,
} from '@/shared/lib/mime-types'
