export { buildFolderTree, countNotesWithinChildren, countUnfiledNotes, createsCircularFolderMove } from './model/domain/folder-tree'
export { hasRemoteUserId, isDeletedNoteRetained, matchesNoteKeyword, normalizeParentIdKey, shouldRefreshNoteUpdated } from './model/domain/note-rules'
export { noteRemoteService } from './model/note-remote-service'
export type { NoteRemoteService, NoteRemoteUpdateResult, NoteWriteMode } from './model/note-remote-service'
export { useNoteSyncExecutorService } from './model/note-sync-executor-service'
export type { ExecuteNoteSyncOperationsParams, NoteSyncExecutionResult } from './model/note-sync-executor-service'
export { buildNoteSyncOperations } from './model/note-sync-plan-service'
export type { BuildNoteSyncOperationsParams, NoteSyncAction, NoteSyncOperation } from './model/note-sync-plan-service'
export { useNoteSyncService } from './model/note-sync-service'
export type { NoteRemoteSyncResult } from './model/note-sync-service'
export { getNotesSync, initializeNotes, useNote } from './model/state/note-store'
export { useNoteFiles } from './model/use-note-files'
export type { FolderTreeNode, Note } from '@/shared/types'
export { normalizeNoteLockFields, NOTE_LOCK_TYPE, NOTE_TYPE } from '@/shared/types'
